### ISSUE TITLE
URL zum Feed

### ISSUE THREAD

**Issue by wojosc** [joelios/iCalFeed#1]
Hi Joel,

wie ist die URL zu dem Feed?

Wenn ich in apple calendar einen abonieren möchte bekomme ich folgende Rückmeldung. Das Bild zeigt einen Hinweis auf eine *.ics Endung. Übersehe ich die irgendwo?
![image](https://user-images.githubusercontent.com/22279621/102914697-fca35f80-4480-11eb-88d3-e61b72585554.png)

if I use my normal URL ein get an error.

**Comment by joelios** [comment]
Hi Wolfram

Die API basis URL lautet `/api/method/icalfeed.icalfeed.utils.calendar.download_calendar?secret=[secret]`

**Comment by wojosc** [comment]
> Hi Wolfram
> 
> Die API basis URL lautet `/api/method/icalfeed.icalfeed.utils.calendar.download_calendar?secret=[secret]`

Thanks. Habe Dir hier das auch für die Nachwelt beantwortet :)
https://github.com/joelios/iCalFeed/pull/2
